### ISSUE TITLE
MonkeyMaster plugin not working on AndroidStudio

### ISSUE THREAD

**Issue by varunatester** [DrkCore/MonkeyMaster#1]
Even though, I have devices running in my emulator,clicking on refresh in not returning device id
AndroidStudio version : 3.6.3
<img width="1322" alt="Screenshot 2020-05-14 at 12 29 47 PM" src="https://user-images.githubusercontent.com/22679401/81902977-a44cdb00-95de-11ea-8c4e-787f87fd7073.png">

**Comment by 4qnInsuide** [comment]
same issue with 4.0

**Comment by DrkCore** [comment]
Sorry for reply so late, it has been a long time since the last commit.

I would refactor it in some days.

**Comment by DrkCore** [comment]
After careful consideration, I think it might be a good time to announce that **this plugin project is DEPRECATED**.

Nowadays, instead of a IDE plugin, a simple script file could do the same thing and might  be even better than this.
